server:
  port: 2022

# OracleDB connection settings
spring:
  jpa:
    hibernate:
      ddl-auto: update
  # Settings for the oracle connection
  datasource:
    url:
      jdbc:oracle:thin:@localhost:1521:xe
    username:
      system
    password:
      12345
    driver-class-oracle:
      jdbc:
        driver:
          OracleDriver
